# Generated by Django 3.0.7 on 2020-06-29 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField()),
                ('is_avail', models.BooleanField(default=True)),
                ('table_id', models.IntegerField()),
            ],
        ),
    ]
