# Generated by Django 3.0.7 on 2020-06-29 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tables',
            name='table_id',
            field=models.IntegerField(unique=True),
        ),
    ]
