# Generated by Django 3.0.7 on 2020-07-05 06:01

import book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='tables',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.TimeField(validators=[book.models.valid_time]),
        ),
    ]
