# Generated by Django 3.0.7 on 2020-07-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_waiting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waiting',
            name='add_time',
            field=models.TimeField(null=True),
        ),
    ]
