# Generated by Django 3.0.7 on 2020-07-05 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20200705_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waiting',
            name='add_time',
            field=models.TimeField(default=datetime.time(20, 22, 27, 948839)),
        ),
    ]
