# Generated by Django 3.0.7 on 2020-07-07 04:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0009_auto_20200706_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='tables',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='waiting',
            name='add_time',
            field=models.TimeField(default=datetime.time(10, 27, 44, 240056)),
        ),
    ]
