# Generated by Django 3.0.7 on 2020-07-09 03:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_auto_20200707_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waiting',
            name='table',
        ),
        migrations.AlterField(
            model_name='waiting',
            name='add_time',
            field=models.TimeField(default=datetime.time(9, 21, 31, 783918)),
        ),
    ]
